### ISSUE TITLE
예금 상품 삭제 관련

### ISSUE THREAD

**Issue by Eundms** [SSU-PaceMaker/taxpayer#30]
`/*
    JoinDeposit 
    : 학생은 하나의 예금에만 가입할 수 있다.
*/

const mongoose =require('mongoose')
const joindepositSchema = mongoose.Schema({
    productId:{/*어떤 상품을*/
        type: mongoose.Schema.Types.ObjectId, 
        ref:'Deposit',
        require:true
    },
    studentId:{/*어떤 학생이 가입하였는가*/
        type: mongoose.Schema.Types.ObjectId, 
        ref:'JoinedUser',
        require:true
    },
    /*해지시 돈 받을 통장 - 학생1=통장1이기에 없어도 됨
    accountId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Account',
        require:true
    },*/
    amount:{/*얼마나 예금하였는가*/
        type:Number,
        require:true
    },
    //가입일 - 항상 해지시점과 비교해서 interestRate 구하기
    createdAt:{
        type:Date,
        default:Date.now
    },
    //해지 시점
    closedAt:{
        type:Date
    },
    isClosed:{//해지되었는가 - 해지되었다면, 한달에 한번 싹다 없애버리자
        type:Boolean,
        default:false
    }
})
const JoinDeposit = mongoose.model('JoinDeposit', joindepositSchema)
module.exports = {JoinDeposit}

/*
    Deposit
    - Class에 속함
    : 예금 상품 종류
*/
const mongoose =require('mongoose')
const depositSchema = mongoose.Schema({
    classId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Class",
        require:true
    },
    name:{/*예금 상품 이름*/
        type:String,
        require:true
    },
    description:{/*설명*/
        type:String,
        default:''
    },
    interestRate:{/*기본 이율(%) : 최소 가입 기간을 지켰을 때*/
        type:Number,
        default:0,
    },
    minAmount:{/* 최소 가입 금액 */
        type:Number,
        default:0
    },
    minduration:{/* 최소 가입 기간(day)- 이전에는 원금만 받고, 이후는 가입금액*rate */
        type:Number,
        require:true
    },
    maxduration:{/*최대 가입 기간(day)*/
        type:Number,
        require:true
    },
    rateBasedDuration:[{/*기간 별 이율-최소 가입기간==최대가입기간=>해당없음*/
        additionalRate:{
            type:Number,
            require:true
        },
        duration:{/*최소 가입 기간 이후 ~ 최대 가입 기간 이전 (**일 이상)*/
            type:Number,
            require:true
        }
    }],
    joinPossible:{/*신규가입가능여부*/
        type:Boolean,
        default:true,
    }
})
const Deposit = mongoose.model('Deposit', depositSchema)
module.exports = {Deposit}
`

이런식으로 모델을 구성했는 데, Deposit을 삭제할 때 괜찮을 지 리뷰 부탁드립니다.

**Comment by Eundms** [comment]
@noino0819 리뷰해주세요

**Comment by noino0819** [comment]
Deposit을 삭제할때에는 다음과 같은 조건들을 확인해야합니다.
1. 해당하는 예금상품에 어떤 학생도 존재하지 않는다.
2. 해당하는 예금상품은 더이상 열리지 않음을 선생님에게 확인받는다.

==============================================
이와같은 상황을 고려했을때 
JoinDeposit에 이 예금 상품({productId:req.params.id})에 가입중인 사람이 있다면, (isClosed:false)
Deposit의 joinPossible 만 true로 하는것이 좋아보입니다.
해당하는 부분은 학생에게 보이지 않습니다.

1.
직접 삭제를 해야된다면 JoinDeposit을 productId로 aggregate해서 isClosed:false가 없다면, 알아서 삭제
또한, 삭제구간에 대해서는 항상확인할 필요가 없으므로(데이터 로딩에 대한 문제) 주기적인 기간을 정해 확인하는것이 좋아보입니다.
2.
이외에도, 만약 JoinDeposit에 가입 중인 사람(isClosed:false)이 없다면, 바로 즉시 2-1)JoinDeposit에서 {productId:req.params.id}로 삭제하는 방법도 괜찮아 보입니다.

**Comment by Eundms** [comment]
아 감사합니다!
주기적으로 Deposit의 joinPossible 필드가 false인 예금상품에 대해 
해당 예금 상품에 아직 가입 유지중인 학생이 없다면, 관련 값들을 삭제하면 되겠네요
